blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Blog(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='Title',
        help_text='Enter the title of the post',
    )
    slug = models.CharField(
        max_length=150,
        verbose_name='Slug',
        blank=True,
        null=True,
    )
    body = models.TextField(
        verbose_name='Body',
        help_text='Enter the text',
    )
    preview = models.ImageField(
        upload_to='blog/photo',
        verbose_name='Photo',
        help_text='Add a photo',
        blank=True,
        null=True,
    )
    created_at = models.DateField(
        verbose_name='Publication date',
        blank=True,
        null=True,
        default=timezone.now
    )
    is_published = models.BooleanField(
        verbose_name='Published',
        default=True,
    )
    views_count = models.PositiveIntegerField(
        verbose_name='Views',
        default=0,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'slug', 'preview', 'created_at', 'is_published', 'views_count',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'slug', 'preview', 'created_at', 'is_published', 'views_count',)

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
   <div class="container">
       <div class="row-6">
           <div class="col-6">
               <form class="row" method="post" enctype="multipart/form-data">
                   <div class="card">
                       <div class="card-body">
                           {% csrf_token %}
                           <p>Are you sure you want to delete'{{ object.title }}'?</p>
                       </div>
                       <button type="submit" class="btn btn-danger">Confirm</button>
                       <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Cancel</a>
                   </div>
               </form>
           </div>
       </div>
   </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load my_tags %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ object.preview }}">
            <div class="card-body">
              <p class="card-text">{{ object.title }}</p>
              {{ object.slug }}
              <p class="card-text">{{ object.body }}</p>
              Views: {{ object.views_count }}
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:list'%}" role="button">Return</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
   <div class="container">
       <div class="row-6">
           <div class="col">
               <form class="row" method="post" enctype="multipart/form-data">
                   <div class="card">
                       <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                       </div>
                       <button type="submit" class="btn btn-success">
                           {% if object %}
                               Save
                           {% else %}
                               Create
                           {% endif %}
                       </button>
                   </div>
               </form>
           </div>
       </div>
   </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load my_tags %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ blog.preview }}">
            <div class="card-body">
              <p class="card-text">{{ object.title }}</p>
              <p class="card-text">{{ object.body }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:view' object.pk %}" role="button">View</a>
                  <a class="btn btn-primary" href="{% url 'blog:edit' object.pk %}" role="button">Edit</a>
                  <a class="btn btn-primary" href="{% url 'blog:delete' object.pk %}" role="button">Delete</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}